export const ADD_RATING_TO_PRODUCT_REQUEST = 'ADD_RATING_TO_PRODUCT_REQUEST'; 
export const ADD_RATING_TO_PRODUCT_SUCCESS = 'ADD_RATING_TO_PRODUCT_SUCCESS'; 
export const ADD_RATING_TO_PRODUCT_FAILURE = 'ADD_RATING_TO_PRODUCT_FAILURE'; 

export const GET_RATING_REQUEST = 'GET_RATING_REQUEST'
export const GET_RATING_SUCCESSS = 'GET_RATING_SUCCESS'
export const GET_RATING_FAILURE = 'GET_RATING_FAILURE'