export const ADD_WISH_ITEM_REQUEST = 'ADD_WISH_ITEM_REQUEST'
export const ADD_WISH_ITEM_SUCCESS = 'ADD_WISH_ITEM_SUCCESS'
export const ADD_WISH_ITEM_FAILURE = 'ADD_WISH_ITEM_FAILURE'

export const GET_WISH_REQUEST = 'GET_WISH_REQUEST'
export const GET_WISH_SUCCESSS = 'GET_WISH_SUCCESS'
export const GET_WISH_FAILURE = 'GET_WISH_FAILURE'

export const REMOVE_WISH_ITEM_REQUEST = 'REMOVE_WISH_ITEM_REQUEST'
export const REMOVE_WISH_ITEM_SUCCESSS = 'REMOVE_WISH_ITEM_SUCCESS'
export const REMOVE_WISH_ITEM_FAILURE = 'REMOVE_WISH_ITEM_FAILURE'