export const GET_DASHBOARD_STATS_REQUEST = 'GET_DASHBOARD_STATS_REQUEST';
export const GET_DASHBOARD_STATS_SUCCESS = 'GET_DASHBOARD_STATS_SUCCESS';
export const GET_DASHBOARD_STATS_FAILURE = 'GET_DASHBOARD_STATS_FAILURE';

export const GET_LATEST_ORDERS_REQUEST = 'GET_LATEST_ORDERS_REQUEST';
export const GET_LATEST_ORDERS_SUCCESS = 'GET_LATEST_ORDERS_SUCCESS';
export const GET_LATEST_ORDERS_FAILURE = 'GET_LATEST_ORDERS_FAILURE';

export const GET_WEEKLY_STATS_REQUEST = 'GET_WEEKLY_STATS_REQUEST';
export const GET_WEEKLY_STATS_SUCCESS = 'GET_WEEKLY_STATS_SUCCESS';
export const GET_WEEKLY_STATS_FAILURE = 'GET_WEEKLY_STATS_FAILURE';

export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';

export const GET_CATEGORY_DISTRIBUTION_REQUEST = 'GET_CATEGORY_DISTRIBUTION_REQUEST';
export const GET_CATEGORY_DISTRIBUTION_SUCCESS = 'GET_CATEGORY_DISTRIBUTION_SUCCESS';
export const GET_CATEGORY_DISTRIBUTION_FAILURE = 'GET_CATEGORY_DISTRIBUTION_FAILURE';
