export const ADD_REVIEW_TO_PRODUCT_REQUEST = 'ADD_REVIEW_TO_PRODUCT_REQUEST'; 
export const ADD_REVIEW_TO_PRODUCT_SUCCESS = 'ADD_REVIEW_TO_PRODUCT_SUCCESS'; 
export const ADD_REVIEW_TO_PRODUCT_FAILURE = 'ADD_REVIEW_TO_PRODUCT_FAILURE'; 

export const GET_REVIEW_REQUEST = 'GET_REVIEW_REQUEST'
export const GET_REVIEW_SUCCESSS = 'GET_REVIEW_SUCCESS'
export const GET_REVIEW_FAILURE = 'GET_REVIEW_FAILURE'